export const styles = {
  shell: 'flex h-svh bg-neutral-100 text-neutral-900',
  sidebar: 'flex w-60 shrink-0 flex-col border-r border-neutral-200 bg-white',
  brand: 'px-4 py-4 text-sm font-semibold tracking-tight',
  nav: 'flex flex-col gap-1 px-2',
  navLink: 'rounded-sm px-3 py-2 text-sm',
  navLinkActive: 'bg-neutral-900 text-white',
  navLinkIdle: 'text-neutral-700 hover:bg-neutral-100',
  header: 'flex h-14 shrink-0 items-center justify-between border-b border-neutral-200 bg-white px-6',
  headerMeta: 'text-sm text-neutral-500',
  headerUser: 'flex items-center gap-3 text-sm',
  headerAction: 'text-sm text-neutral-500 hover:text-neutral-900',
  loginScreen: 'flex min-h-svh items-center justify-center bg-neutral-100 p-6',
  loginPanel: 'w-full max-w-sm space-y-6',
  loginBrand: 'text-center text-sm font-semibold tracking-tight',
  contentColumn: 'flex min-w-0 flex-1 flex-col',
  main: 'min-h-0 flex-1 overflow-auto p-6',
  page: 'space-y-6',
  pageHeader: 'flex items-start justify-between gap-4',
  pageTitle: 'text-2xl font-semibold',
  pageDescription: 'mt-1 text-sm text-neutral-600',
  card: 'rounded border border-neutral-200 bg-white p-4',
  cardFlush: 'overflow-hidden rounded border border-neutral-200 bg-white',
  summaryGrid: 'grid gap-4 sm:grid-cols-3',
  summaryLabel: 'text-sm text-neutral-500',
  summaryValue: 'mt-2 text-2xl font-semibold',
  salesLayout: 'grid gap-6 lg:grid-cols-[2fr_1fr]',
  posScreen: '-m-6 flex min-h-[calc(100svh-3.5rem)] bg-[#0f1216] text-white',
  posFrame: 'grid min-h-[calc(100svh-3.5rem)] min-w-0 flex-1 xl:grid-cols-[minmax(0,1fr)_26rem]',
  posStage: 'flex min-w-0 flex-col gap-5 p-6',
  posStoreRow: 'flex flex-wrap gap-2',
  posStoreChip: 'rounded-full border px-4 py-2 text-sm',
  posStoreChipIdle: 'border-white/15 bg-white/5 text-white/80',
  posStoreChipActive: 'border-emerald-400 bg-emerald-400 text-neutral-950',
  posScanner: 'flex min-h-14 items-center gap-3 rounded-2xl border border-white/10 bg-white/5 px-4',
  posScannerInput: 'w-full bg-transparent font-mono text-lg tracking-wide text-white outline-none placeholder:text-white/35',
  posGrid: 'grid gap-4 sm:grid-cols-2 xl:grid-cols-3',
  posTile: 'flex flex-col gap-4 rounded-2xl border p-4 text-left transition',
  posTileIdle: 'border-white/10 bg-white/[0.06] hover:border-emerald-400/70 hover:bg-white/[0.1]',
  posTileMuted: 'cursor-not-allowed border-white/5 bg-white/[0.03] opacity-40',
  posCart: 'flex min-h-[calc(100svh-3.5rem)] flex-col border-white/10 bg-[#161b22] p-6 xl:border-l',
  posCartLine: 'flex items-center justify-between gap-3 border-b border-white/10 py-4 text-sm',
  posQtyButton: 'h-8 w-8 rounded-full border border-white/20 text-white',
  posPayRow: 'grid grid-cols-2 gap-2',
  posPayButton: 'w-full rounded-2xl bg-emerald-400 px-4 py-4 text-base font-semibold text-neutral-950',
  posGhostButton: 'w-full rounded-2xl border border-white/15 px-4 py-3 text-sm text-white/80',
  form: 'space-y-4',
  formGrid: 'grid gap-4 sm:grid-cols-2',
  field: 'flex flex-col gap-1 text-sm',
  fieldLabel: 'text-neutral-600',
  input: 'rounded-sm border border-neutral-200 px-3 py-2',
  buttonPrimary: 'rounded-sm bg-neutral-900 px-4 py-2 text-sm text-white',
  badge: 'inline-flex rounded-sm px-2 py-1 text-xs font-medium',
  badgeMuted: 'bg-neutral-100 text-neutral-600',
  badgeSuccess: 'bg-emerald-50 text-emerald-700',
  badgeWarning: 'bg-amber-50 text-amber-700',
  table: 'w-full text-left text-sm',
  tableHead: 'bg-neutral-50 text-neutral-500',
  tableHeadCell: 'px-4 py-3 font-medium',
  tableRow: 'border-t border-neutral-200',
  tableCell: 'px-4 py-3 text-neutral-900',
  tableCellMuted: 'px-4 py-3 text-neutral-600',
  tableEmpty: 'px-4 py-6 text-sm text-neutral-500',
  definitionList: 'mt-3 grid gap-2 text-neutral-600',
  definitionRow: 'flex justify-between',
  definitionValue: 'text-neutral-900',
  sectionTitle: 'font-semibold',
}
