export const styles = {
  shell: 'flex h-svh bg-neutral-100 text-neutral-900',
  sidebar: 'flex w-60 shrink-0 flex-col border-r border-neutral-200 bg-white',
  brand: 'px-4 py-4 text-sm font-semibold tracking-tight',
  nav: 'flex flex-col gap-1 px-2',
  navLink: 'rounded-sm px-3 py-2 text-sm',
  navLinkActive: 'bg-neutral-900 text-white',
  navLinkIdle: 'text-neutral-700 hover:bg-neutral-100',
  header: 'flex h-14 shrink-0 items-center justify-between border-b border-neutral-200 bg-white px-6',
  headerMeta: 'text-sm text-neutral-500',
  headerUser: 'flex items-center gap-3 text-sm',
  headerAction: 'text-sm text-neutral-500 hover:text-neutral-900',
  loginScreen: 'flex min-h-svh items-center justify-center bg-neutral-100 p-6',
  loginPanel: 'w-full max-w-sm space-y-6',
  loginBrand: 'text-center text-sm font-semibold tracking-tight',
  contentColumn: 'flex min-w-0 flex-1 flex-col',
  main: 'min-h-0 flex-1 overflow-auto p-6',
  page: 'space-y-6',
  pageTitle: 'text-2xl font-semibold',
  pageDescription: 'mt-1 text-sm text-neutral-600',
  card: 'rounded border border-neutral-200 bg-white p-4',
  cardFlush: 'overflow-hidden rounded border border-neutral-200 bg-white',
  summaryGrid: 'grid gap-4 sm:grid-cols-3',
  summaryLabel: 'text-sm text-neutral-500',
  summaryValue: 'mt-2 text-2xl font-semibold',
  salesLayout: 'grid gap-6 lg:grid-cols-[2fr_1fr]',
  form: 'space-y-4',
  formGrid: 'grid gap-4 sm:grid-cols-3',
  field: 'flex flex-col gap-1 text-sm',
  fieldLabel: 'text-neutral-600',
  input: 'rounded-sm border border-neutral-200 px-3 py-2',
  badge: 'inline-flex rounded-sm px-2 py-1 text-xs font-medium',
  badgeMuted: 'bg-neutral-100 text-neutral-600',
  badgeSuccess: 'bg-emerald-50 text-emerald-700',
  badgeWarning: 'bg-amber-50 text-amber-700',
  table: 'w-full text-left text-sm',
  tableHead: 'bg-neutral-50 text-neutral-500',
  tableHeadCell: 'px-4 py-3 font-medium',
  tableRow: 'border-t border-neutral-200',
  tableCell: 'px-4 py-3 text-neutral-900',
  tableCellMuted: 'px-4 py-3 text-neutral-600',
  definitionList: 'mt-3 grid gap-2 text-neutral-600',
  definitionRow: 'flex justify-between',
  definitionValue: 'text-neutral-900',
  sectionTitle: 'font-semibold',
} as const
